server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # PWA + SPA
  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(js|css|png|svg|webp|woff2)$ {
    expires 7d;
    add_header Cache-Control "public";
  }

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;
}
