import type { Policy } from "./types.js";

/** Bundled default policy — international persona pack. */
export const defaultPolicy: Policy = {
  version: 1,
  name: "default",
  fail_closed: true,
  require_human_approval: true,
  replacements: {
    email: ["user@example.com", "contact@example.org", "hello@example.net"],
    person_name: [
      "Amara Okafor",
      "Yuki Tanaka",
      "Sofía Mendoza",
      "Lars Nielsen",
      "Priya Sharma",
      "Chen Wei",
      "Fatima Al-Hassan",
      "Nina Petrović",
      "Mateo Rossi",
      "Aisha Diallo",
    ],
    phone: [
      "+44 7700 900123",
      "+81 90-1234-5678",
      "+55 11 98765-4321",
      "+49 151 12345678",
      "+91 98765 43210",
      "+234 801 234 5678",
    ],
    hostname: ["app.example.com", "console.example.org"],
    account_id: ["usr_example_001", "usr_example_002", "acct_demo_100"],
    org_name: [
      "Meridian GmbH",
      "Sakura Systems",
      "Northwind Ltd",
      "Andes Digital",
      "Lagos Labs",
    ],
    ip: ["10.0.0.10", "10.0.0.20", "192.168.0.10"],
    address: [
      "100 Example Street, London",
      "2-1 Example-cho, Shibuya",
      "Av. Ejemplo 500, São Paulo",
    ],
  },
  vocabulary: {
    keep: [],
    redact: [],
  },
  categories: {
    api_key: { action: "redact_block", severity: "critical" },
    token: { action: "redact_block", severity: "critical" },
    password: { action: "redact_block", severity: "critical" },
    url_secret: { action: "redact_block", severity: "critical" },
    financial: { action: "redact_block", severity: "critical" },
    email: { action: "replace_text", severity: "high" },
    phone: { action: "replace_text", severity: "high" },
    person_name: { action: "replace_text", severity: "high" },
    address: { action: "replace_text", severity: "high" },
    account_id: { action: "replace_text", severity: "high" },
    ip: { action: "replace_text", severity: "high" },
    hostname: { action: "replace_text", severity: "medium" },
    org_name: { action: "replace_text", severity: "medium" },
    face: { action: "blur", severity: "high" },
    free_text_pii: { action: "redact_block", severity: "high" },
    other: { action: "redact_block", severity: "medium" },
  },
  export: {
    format: "png",
    strip_metadata: true,
    max_width: 2400,
  },
};
